const v = {
  // POST
  REGISTRO_C:  process.env.NEXT_PUBLIC_REGISTRO_CLIENTE,
  REGISTRO_A:  process.env.NEXT_PUBLIC_REGISTRO_ADMIN,
  LOGIN_ADMIN: process.env.NEXT_PUBLIC_LOGIN_ADMIN,
  FIND_NOTI_C: process.env.NEXT_PUBLIC_FIND_BY_DATE_CL,
  FILTER_CLI:  process.env.NEXT_PUBLIC_FILTER_CLIENTS,

  // GET
  ALL_CLIENTS: process.env.NEXT_PUBLIC_GET_ALL_CLIENTS,
  GET_MOVES:   process.env.NEXT_PUBLIC_GET_ALL_MOVE,
  ONE_CLIENTS: process.env.NEXT_PUBLIC_GET_ONE_CLIENTS,
  GET_NOTIFY:  process.env.NEXT_PUBLIC_GET_NOTIFY_CLI,
  GET_ADMINS:  process.env.NEXT_PUBLIC_GET_ALL_ADMINS,
  GET_ADMIN:   process.env.NEXT_PUBLIC_GET_ONE_ADMIN,
  GET_AD_EM:   process.env.NEXT_PUBLIC_GET_ADMIN,

  // PUT
  EDIT_CLIENT: process.env.NEXT_PUBLIC_UPDATE_CLIENT,

  // DELETE
  DEL_CLIENT:  process.env.NEXT_PUBLIC_DELETE_CLIENT,
  DEL_ADMIN:   process.env.NEXT_PUBLIC_DELETE_ADMIN,
  DEL_DEVICE:  process.env.NEXT_PUBLIC_DELETE_DEVICE
}

export default v